// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTOSTRAFE_H
#define AUTOSTRAFE_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class autoStrafe: public Command {
public:
	autoStrafe();
	autoStrafe(double setPoint, double timeoutInSeconds);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
public:
	enum Purpose
	{
		rightToAvoidContainerBeforeDrivingForward,
		leftToAvoidYellowToteBeforeDrivingForward,
		leftFromLandfillZone,
		rightToAvoidContainerBeforeElevatorRises,
	};

	enum EndCondition
	{
		encoderDistance,
		timeOut,
		encoderDistanceAndTimeOut,
	};
private:
	double mDistance;

	// Handles timeout for the entire command
	Timer mTimeoutTimer;
	double mTimeout;

	// Handles timeout for change in encoder values
	Timer mTimeoutForEncoderChange;
	double mPreviousEncoderReading;
};

#endif
