// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "autoTestRightThreeTote.h"
#include "autoDrive.h"
#include "Delay.h"
#include "zeroLevel.h"
#include "autoHaySqueezerOpen.h"

autoTestRightThreeTote::autoTestRightThreeTote() {
	// Push the third yellow Tote into the Auto Zone
	// While doing so, begin dropping the other two yellow Totes
	AddParallel(new autoDrive(5500));

	AddSequential(new Delay(0.5));
	AddSequential(new zeroLevel());

	// forfeit contact with the Tote stack
	AddSequential(new autoHaySqueezerOpen());
}
