// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "autoLeftDriveThreeToteNarrow.h"
#include "autoHaySqueezerOpen.h"
#include "zeroLevel.h"
#include "haySqueezerClose.h"
#include "Delay.h"
#include "oneLevel.h"
#include "autoDrive.h"
#include "autoStrafe.h"

autoLeftDriveThreeToteNarrow::autoLeftDriveThreeToteNarrow() {

	const double timeToRemoveContainers = 2.0;
	const double encoderDistanceBetweenTotes = 500.0;

	// Drop the elevator down and pick up the yellow Tote
	AddSequential(new autoHaySqueezerOpen());
	AddSequential(new zeroLevel());
	AddSequential(new haySqueezerClose());
	AddSequential(new Delay(0.5)); // let the hay squeezer close

	// Lift the Tote off of the ground
	AddSequential(new oneLevel());

	// Drive to the second Tote
	AddSequential(new autoDrive(encoderDistanceBetweenTotes));

	// Drop the elevator down to let the tabs pick up the next Tote
	AddSequential(new zeroLevel());

	// Lift the two Totes off of the ground
	AddSequential(new oneLevel());

	// Drive to the third Tote
	AddSequential(new autoDrive(encoderDistanceBetweenTotes));

	// Drop the elevator down to let the tabs pick up the next Tote
	AddSequential(new zeroLevel());

	// Lift the three Totes off of the ground
	AddSequential(new oneLevel());

	// Strafe into the Auto Zone
	AddSequential(new autoStrafe(500.0, 5.0));

	// Drop the stack and back away from it
	AddSequential(new zeroLevel());
	AddSequential(new autoDrive(-400.0));
}
