// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Delay.h"
#include "autoHaySqueezerOpen.h"
#include "zeroLevel.h"
#include "haySqueezerClose.h"
#include "twoLevel.h"
#include "autoStrafeToToteLeft.h"
#include "autoDrive.h"
#include "autoStrafe.h"
#include "autoWideStack.h"
#include "autoLightStrafeLeft.h"
#include "autoLeftStrafeThreeTote.h"
#include "spoolAboveContainer.h"
#include "autoWideStack.h"
#include "autoStrafeToToteLeft.h"
#include "autoStrafeUntilNoYellowTote.h"

void autoLeftStrafeThreeTote::pickUpToteAndGoToNextOne() {
	AddSequential(new autoHaySqueezerOpen());

	// Lower the elevator and pick up the tote
	AddSequential(new zeroLevel());
	AddSequential(new haySqueezerClose());
	AddSequential(new Delay(0.3)); // to let the hay squeezer close

	// Go above container height
	AddParallel(new spoolAboveContainer());

	AddSequential(new autoStrafeUntilNoYellowTote());

	//Strafe to the right to the second tote
	AddSequential(new autoStrafeToToteLeft());
}

autoLeftStrafeThreeTote::autoLeftStrafeThreeTote() {


	//Strafe slightly left to clear second container
	AddSequential(new autoLightStrafeLeft());		//Banner Sensor Dependent

	// lower elevator directly above second tote
	AddSequential(new autoWideStack());

	// move back over second tote
	AddSequential(new autoStrafeToToteLeft());

	// Push the third yellow Tote into the Auto Zone
	// While doing so, begin dropping the other two yellow Totes
	AddParallel(new autoDrive(autoDrive::Purpose::threeToteAuto,
	true, true, false));

	AddSequential(new Delay(0.5));
	AddSequential(new zeroLevel());

	// forfeit contact with the Tote stack
	AddSequential(new autoHaySqueezerOpen());


//.............................................................. Second Tote

	// Strafe left until in front of second container
	// AddSequential(new autoStrafe(Robot::prefs->GetDouble("distanceFirstToteToSecondContainer", 0.0)));

	// Drive forward to push the container sufficiently away
	// AddSequential(new autoDrive(Robot::prefs->GetDouble("distancePushContainerAway", 0.0)));

	// Drive back to position for strafing
	// AddSequential(new autoDrive(-1 * Robot::prefs->GetDouble("distancePushContainerAway", 0.0)));

	// Drive to the yellow tote


	//Strafe to the left to tote
	//AddSequential(new autoStrafeToToteLeft());
	/*
	//Strafe slightly right to clear container
	//AddSequential(new autoStrafe(500));
	//lower elevator directly above tote
	AddSequential(new Delay(0.3));
	//
	AddSequential(new autoLightStrafeRight());

	AddSequential(new autoWideStack());
	//move back over tote
	//AddSequential(new autoStrafe(-500));
	//lower elevator on tote
	//open hay squeezer
	AddSequential(new autoStrafeToToteLeft());

	AddSequential(new autoHaySqueezerOpen());
	//
	AddSequential(new zeroLevel());
	//close hay squeezer on tote
	AddSequential(new haySqueezerClose());
	//delay
	AddSequential(new Delay(0.5));
	//
	//AddSequential(new autoStrafe(500));
	//
	AddSequential(new twoLevel());
//..............................................................Third Tote
	//Strafe to the left to tote
	AddSequential(new autoStrafeToToteLeft());
	//Strafe slightly right to clear container
	//AddSequential(new autoStrafe(500));
	//lower elevator directly above tote
	AddSequential(new Delay(0.3));

	AddSequential(new autoLightStrafeRight());

	AddSequential(new autoWideStack());
	//move back over tote
	//AddSequential(new autoStrafe(-500));
	//open hay squeezer
	AddSequential(new autoHaySqueezerOpen());
	//lower elevator on tote
	AddSequential(new zeroLevel());
	//close hay squeezer on tote
	AddSequential(new haySqueezerClose());
	//
	//AddSequential(new autoStrafe(500));
	AddSequential(new Delay(0.5));

	AddSequential(new twoLevel());


	//............................................................Drive
	//
	AddSequential(new autoDrive(7600));
	*/
}
