// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "autoHaySqueezerOpen.h"
#include "zeroLevel.h"
#include "haySqueezerClose.h"
#include "spoolAboveContainer.h"
#include "autoStrafeToToteRight.h"
#include "autoDrive.h"
#include "autoStrafe.h"
#include "autoWideStack.h"
#include "autoLightStrafeRight.h"
#include "autoStrafeToToteLeft.h"
#include "Delay.h"

#include "autoStrafeRightThreeTote.h"

autoStrafeRightThreeTote::autoStrafeRightThreeTote() {

	AddSequential(new autoHaySqueezerOpen());

	// Lower the elevator and pick up the first tote
	AddSequential(new zeroLevel());
	AddSequential(new haySqueezerClose());
	AddSequential(new Delay(0.3)); // to let the hay squeezer close

	// Strafe Slightly to the right to avoid knocking first container down
	// AddSequential(new autoStrafe(600, 0.5));

	// Go above container height
	AddSequential(new spoolAboveContainer());

	//Strafe to the right to the second tote
	AddSequential(new autoStrafeToToteRight());

	//Strafe slightly right to clear second container
	AddSequential(new autoLightStrafeRight());		//Banner Sensor Dependent

	// lower elevator directly above second tote
	AddSequential(new autoWideStack());

	// move back over second tote
	AddSequential(new autoStrafeToToteLeft());

	// open hay squeezer
	AddSequential(new autoHaySqueezerOpen());

	// lower elevator and pick up second tote
	AddSequential(new zeroLevel());
	AddSequential(new haySqueezerClose());
	AddSequential(new Delay(0.3));

	// Strafe slightly to the right to avoid knocking the second container down
	// AddSequential(new autoStrafe(500, 0.5));

	// Go above container height
	AddSequential(new spoolAboveContainer());

	//Strafe to the right to third Tote
	AddSequential(new autoStrafeToToteRight());

	// Push the third yellow Tote into the Auto Zone
	// While doing so, begin dropping the other two yellow Totes
	AddParallel(new autoDrive(5500));
	AddSequential(new zeroLevel());

	// Open the hay squeezer and back up
	// to forfeit contact with the Tote stack
	AddParallel(new autoHaySqueezerOpen());
	AddSequential(new autoDrive(-450));
}
