// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#ifndef AUTOLEFTDRIVETHREETOTENARROW_H
#define AUTOLEFTDRIVETHREETOTENARROW_H

#include "Commands/CommandGroup.h"

/**
 *
 *
 * @author Wikipedia
 * @commandDescription With this command, the robot will
 * take three yellow Totes to the Auto Zone.
 * The robot will start to the right of the rightmost yellow
 * Tote, and it should be facing to the left.
 * This command assumes the three Container will be moved out of
 * the way after a specified amount of time.
 */
class autoLeftDriveThreeToteNarrow: public CommandGroup {
public:
	autoLeftDriveThreeToteNarrow();
};

#endif
