// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoDriveReverse.h"

#include "SmartDashboard/SmartDashboard.h"

AutoDriveReverse::AutoDriveReverse()

:driveDistance(0.0) , goalDistance(0.0)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void AutoDriveReverse::Initialize() {
	
	goalDistance = Robot::prefs->GetDouble("driveDistanceReverse" , 0.0);

}

// Called repeatedly when this Command is scheduled to run
void AutoDriveReverse::Execute() {
	
	Robot::chassis->robotDrive->MecanumDrive_Cartesian(0.0 , -0.5 , 0.0);

	driveDistance = Robot::chassis->rightFront->GetEncPosition();

}

// Make this return true when this Command no longer needs to run execute()
bool AutoDriveReverse::IsFinished() {
	Robot::prefs->GetDouble("AutoDriveForwardDelay", 0.0);

		if (driveDistance >= goalDistance)
			return true;

			else
				return false;
}

// Called once after isFinished returns true
void AutoDriveReverse::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoDriveReverse::Interrupted() {

}
