// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "intakeIn.h"

intakeIn::intakeIn() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void intakeIn::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void intakeIn::Execute() {
	Robot::intake->intakeRightMotor->Set(1.0);		//Set intake motors to turn on to full power
	Robot::intake->intakeLeftMotor->Set(-1.0);		// (inverted because mirrored, might need changing)
}

// Make this return true when this Command no longer needs to run execute()
bool intakeIn::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void intakeIn::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void intakeIn::Interrupted() {

}
