// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "oneLevel.h"

oneLevel::oneLevel() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::spool);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void oneLevel::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void oneLevel::Execute() {
	Robot::spool->spoolLeftMotor->Set(1.0);
	Robot::spool->spoolRightMotor->Set(1.0);
}

// Make this return true when this Command no longer needs to run execute()
bool oneLevel::IsFinished() {
	bool test;
	double oneToteLevel = Robot::oi->encoderStartingValue -1116;
	if(Robot::spool->spoolRightMotor->GetEncPosition() <=oneToteLevel )
		test = true;
	return test;
}

// Called once after isFinished returns true
void oneLevel::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void oneLevel::Interrupted() {

}
