// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "slideClockRotation.h"

slideClockRotation::slideClockRotation() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::slide);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void slideClockRotation::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void slideClockRotation::Execute() {
	int rightTrigger = 3;
	Robot::slide->slideFrontMotor1->Set(Robot::oi->getdriver()->GetRawAxis(rightTrigger));
	Robot::slide->slideFrontMotor2->Set(Robot::oi->getdriver()->GetRawAxis(rightTrigger));
	Robot::slide->slideRearMotor->Set(Robot::oi->getdriver()->GetRawAxis(rightTrigger) * -1);
}

// Make this return true when this Command no longer needs to run execute()
bool slideClockRotation::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void slideClockRotation::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void slideClockRotation::Interrupted() {

}
