// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "slideCounterClockRotation.h"

slideCounterClockRotation::slideCounterClockRotation() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::slide);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void slideCounterClockRotation::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void slideCounterClockRotation::Execute() {
	double slideSpeed = Robot::prefs->GetDouble("slideSpeed", 1.0);
	Robot::slide->slideFrontMotor1->Set(slideSpeed);
	Robot::slide->slideFrontMotor2->Set(slideSpeed);
	Robot::slide->slideRearMotor->Set(slideSpeed * -1);
}

// Make this return true when this Command no longer needs to run execute()
bool slideCounterClockRotation::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void slideCounterClockRotation::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void slideCounterClockRotation::Interrupted() {

}
