// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "strafeLeft.h"

strafeLeft::strafeLeft() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void strafeLeft::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void strafeLeft::Execute() {
	
	int leftFrontPower = Robot::prefs->GetDouble("leftFrontPower", 1.0) * -1;
	int leftRearPower = Robot::prefs->GetDouble("leftRearPower", 1.0) ;
	int rightFrontPower = Robot::prefs->GetDouble("rightFrontPower", 1.0) ;
	int rightRearPower = Robot::prefs->GetDouble("rightRearPower", 1.0) * -1;

	Robot::chassis->leftFront->Set(leftFrontPower);
	Robot::chassis->leftRear->Set(leftRearPower);
	Robot::chassis->rightFront->Set(rightFrontPower);
	Robot::chassis->rightRear->Set(rightRearPower);
}

// Make this return true when this Command no longer needs to run execute()
bool strafeLeft::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void strafeLeft::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void strafeLeft::Interrupted() {

}
