// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "twoLevel.h"

twoLevel::twoLevel() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::spool);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void twoLevel::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void twoLevel::Execute() {
	//Robot::spool->spoolRightMotor->Set()
}

// Make this return true when this Command no longer needs to run execute()
bool twoLevel::IsFinished() {
	bool test = false;
	/*
	if(Robot::spool->spoolRightMotor->GetEncPosition() <= -1116)
		test = true;
	return test;
	*/
	if(Robot::spool->spoolRightMotor->GetPosition() == -1000)
		cout << "you are there!";
		test = true;
	return test;
}

// Called once after isFinished returns true
void twoLevel::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void twoLevel::Interrupted() {

}
