// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SPOOL_H
#define SPOOL_H
#include "Commands/Subsystem.h"
//#include "WPILib.h"
#include "../CANEncoderPIDInput.h"
#include "../Elevator.h"

#include "CANTalon.h"
#include "PIDController.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Spool: public Subsystem {
private:

	CANTalonEncoderPIDSource* pidInput;

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DoubleSolenoid* breakSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANTalon* spoolRightMotor;
	CANTalon* spoolLeftMotor;
	Spool();
	void InitDefaultCommand();
	PIDController* pidController;
	Elevator* pidOutput;
};

#endif
