// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"
#include "BuiltInAccelerometer.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoDelayTest.h"
#include "Commands/Drive.h"
#include "Commands/PneIntakeOut.h"
#include "Commands/artificialShift.h"
#include "Commands/intakeIn.h"
#include "Commands/intakeOff.h"
#include "Commands/intakeOut.h"
#include "Commands/slideMaster.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	driver = new Joystick(0);
	
	dButtonL3 = new JoystickButton(driver, 9);
	dButtonL3->WhenReleased(new artificialShift());
	dButtonY = new JoystickButton(driver, 4);
	dButtonY->WhileHeld(new intakeIn());
	dButtonA = new JoystickButton(driver, 1);
	dButtonA->WhenReleased(new PneIntakeOut());
	dButtonB = new JoystickButton(driver, 2);
	dButtonB->WhileHeld(new intakeOut());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("artificialShift", new artificialShift());

	SmartDashboard::PutData("Drive", new Drive());

	SmartDashboard::PutData("slideMaster", new slideMaster());

	SmartDashboard::PutData("intakeOut", new intakeOut());

	SmartDashboard::PutData("intakeIn", new intakeIn());

	SmartDashboard::PutData("intakeOff", new intakeOff());

	SmartDashboard::PutData("PneIntakeOut", new PneIntakeOut());

	SmartDashboard::PutData("AutoDelayTest", new AutoDelayTest());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	//multiplier = Robot::prefs->GetDouble("multiplier", 1.0);
	//fullPower = 1.0;
	//enableMultiplier = false;

}
/*
JoystickButton* OI::getdButtonRB()
{
	return dButtonRB;
}

JoystickButton* OI::getdButtonLB()
{
	return dButtonLB;
}
*/
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getdriver() {
	return driver;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

/*

 void OI::setEnableMultiplier(bool isEnable)
{
	enableMultiplier = isEnable;
}

double OI::getMultiplier()
{
	return enableMultiplier ? multiplier : fullPower;
}

bool OI::getEnableMultiplier()
{
	return enableMultiplier;
}
*/



