// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:

	JoystickButton* dButtonRB;
	JoystickButton* dButtonLB;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* driver;
	JoystickButton* dButtonL3;
	JoystickButton* dButtonY;
	JoystickButton* dButtonA;
	JoystickButton* dButtonB;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	double multiplier;
	double fullPower;
	bool enableMultiplier;

public:
	OI();

	double getMultiplier();
	void setEnableMultiplier(bool isEnable);
	bool getEnableMultiplier();

	JoystickButton* getdButtonRB();
	JoystickButton* getdButtonLB();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getdriver();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
