// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"
#include "rumbler.h"

class OI {
private:

	JoystickButton* dButtonRB;
	JoystickButton* dButtonLB;
	JoystickButton* dButtonL3;
//CoDriver Buttons............................................................
	JoystickButton* cYellow;
	JoystickButton* cSmallRed;
	JoystickButton* cSmallBlack;
	JoystickButton* cGreen;

	JoystickButton* cBlue;
	JoystickButton* cWhite;
	JoystickButton* cBlack;
	JoystickButton* cRed;

	/*
	JoystickButton* coButtonA;
	JoystickButton* coButtonB;
	JoystickButton* coButtonX;
	//JoystickButton* coButtonY;
	JoystickButton* coButtonLB;
	JoystickButton* coButtonRB;
	*/
//Timer for rumble of driver controller.......................................
	//Timer* rumbleTimer;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* coDriver;
	Joystick* driver;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

public:
	OI();

	double encoderStartingValue;

//Rumble "Bad" code
	//void singleRumbleTime(int x);
	//void singleRumbleForSomeTime(int x);
	Rumbler* driverRumbler;
	Rumbler* coDriverRumbler;

	JoystickButton* getdButtonRB();
	JoystickButton* getdButtonLB();
	JoystickButton* getdButtonL3();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getdriver();
	Joystick* getcoDriver();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
