// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
DoubleSolenoid* RobotMap::pneIntakeintakeSolenoid = NULL;
DoubleSolenoid* RobotMap::haySqueezerhaySqueezerSolenoid = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	pneIntakeintakeSolenoid = new DoubleSolenoid(0, 0, 7);      
	lw->AddActuator("PneIntake", "intakeSolenoid", pneIntakeintakeSolenoid);
	
	haySqueezerhaySqueezerSolenoid = new DoubleSolenoid(0, 1, 6);      
	lw->AddActuator("HaySqueezer", "haySqueezerSolenoid", haySqueezerhaySqueezerSolenoid);
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
